services:
  - type: web
    name: dead-air-archives
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn DeadAirArchives.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DeadAirArchives.settings  # ✅ should match your actual Django settings module
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: dead-air-db
          property: connectionString

databases:
  - name: dead-air-db
    plan: free
    ipAllowList: []
