services:
  - type: web
    name: dead-air-archives
    env: python
    services:
      - type: web

        buildCommand: |
          pip install -r requirements.txt
          python manage.py collectstatic --no-input
        preDeploy:
          - python manage.py makemigrations
          - python manage.py migrate
        startCommand: gunicorn MyBlog.wsgi:application

        databases:
        - type: postgres
          name: dead-air-db
          plan: free

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MyBlog.settings
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: dead-air-db
          property: connectionString

  - type: postgres
    name: dead-air-db
    ipAllowList: []
    plan: free
