services:
  - type: web
    name: dead-air-archives
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput --verbosity 2
      python manage.py collectstatic --noinput
      

    startCommand: gunicorn MyBlog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MyBlog.settings
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: dead-air-db
          property: connectionString

  - type: postgres
    name: dead-air-db
    ipAllowList: []
    plan: free
