services:
  - type: web
    name: dead-air-archives
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn MyBlog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: MyBlog.settings
      - key: SECRET_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        value: False
