# Generated by Django 5.2.3 on 2025-06-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('ufo', 'UFOs / UAPs'), ('cia', 'CIA & Surveillance'), ('psyops', 'Psychological Ops'), ('censorship', 'Censorship & Big Tech')], max_length=20)),
                ('download', models.FileField(blank=True, null=True, upload_to='vault_downloads/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
